version: "3"
services:
    app:
        container_name: express-mongo-neo4j
        restart: always
        build: ./
        ports:
            - "80:3000"
        volumes:
            - /app/node_modules
        links:
            - mongo
            - neo4j
        depends_on:
            - mongo
            - neo4j
        environment: 
            - NEO4J_URI=bolt://neo4j:7687
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - "27017:27017"
    neo4j:
        container_name: neo4j
        image: neo4j:3.5
        ports:
            - "7687:7687"
            - "7474:7474"
        environment: 
            - NEO4J_AUTH=none
            - NEO4J_LABS=["APOC"]