version: "3"
services:
    app:
        container_name: express-mongo
        restart: always
        build: ./
        ports:
            - "80:3000"
        volumes:
            - /app/node_modules
        links:
            - mongo
            - elasticsearch
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - "27017:27017"
    elasticsearch:
        container_name: elasticsearch
        image: elasticsearch:6.8.12
        ports:
            - "9200:9200"