version: "3"
services:
    app:
        container_name: express-mongo-neo4j
        restart: always
        build: ./
        ports:
            - "80:3000"
        volumes:
            - /app/node_modules
        links:
            - mongo
            - neo4j
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - "27017:27017"
    neo4j:
        container_name: neo4j
        image: neo4j
        ports:
            - "17474:7474"